### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/discovery-dispatcher#43]
currently 82% - aim for acceptable coverage

Step1: pairing for 1-2 hours to analyze and then flesh out action further.

**Comment by mejackreed** [comment]
Files where coverage is lacking:

| COVERAGE | FILE | LINES | RELEVANT | COVERED | MISSED | HITS/LINE |
| --- | --- | --- | --- | --- | --- | --- |
| 0.0 | app/controllers/items_controller.rb | 12 | 12 | 0 | 12 | 0.0 |
| 72.5 | lib/discovery_dispatcher/purl_fetcher_reader.rb | 74 | 40 | 29 | 11 | 3.0 |
| 75.0 | lib/discovery_dispatcher/monitor.rb | 28 | 12 | 9 | 3 | 1.0 |
| 88.89 | app/controllers/about_controller.rb | 14 | 9 | 8 | 1 | 1.0 |
| 96.97 | lib/discovery_dispatcher/indexing_job.rb | 69 | 33 | 32 | 1 | 1.0 |

For `app/controllers/items_controller.rb`, #30 really needs to be addressed first. What is the expected behavior of this? Is this route what is defined in https://consul.stanford.edu/display/GRYPHONDOR/Discovery+Release+Dispatcher ? 

> As a Web Services app supporting an API for reindexing (a secondary priority for the first Dispatcher sprint, Summer 2016)
> It  supports the /collections/{druid}  call for a specific collection to get members in order to send appropriate re-index signals for all index targets. 
> It supports the /items/{druid} call to reindex a specific object in all relevant index targets
